### ISSUE TITLE
Requires PHP 5.4

### ISSUE THREAD

**Issue by grokcore** [ronan-gloo/jade-php#2]
"Jade template engine ported to PHP 5.3" isn't quite right.
Thanks :) 
addendum: As far as I know, this is only because of the javascript style array syntax that's used.

conclusion: Yes, it's very simple to change the syntax for 5.3 in the one Jade.php file.

**Comment by ronan-gloo** [comment]
Right, fixed with https://github.com/ronan-gloo/jade-php/commit/bc1f72d45bee606e40ab5a52bd1e69683677786e
Thanks
